version: "3.8"

networks:
  app-networks:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - app-networks

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./php-worker/supervisord.d:/etc/supervisord.d
    ports:
      - "9000:9000"
    networks:
      - app-networks

  php-worker:
    build:
      context: ./php-worker
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./php-worker/supervisord.d:/etc/supervisor/supervisord.d
      - ./logs/supervisor:/etc/supervisor/logs
    networks:
      - app-networks

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/.auezov-docker/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - app-networks

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-networks

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - ~/.auezov-docker/redis:/data
    command: --requirepass docker
    ports:
      - "6379:6379"
    networks:
      - app-networks

  redis-webui:
    build:
      context: ./redis-webui
      dockerfile: Dockerfile
    environment:
      - ADMIN_USER=docker
      - ADMIN_PASS=docker
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=docker
    ports:
      - "8082:80"
    depends_on:
      - redis
    networks:
      - app-networks